#!/usr/bin/env python

import __builtin__
from sys import argv
import importlib

modules, options = [], []
for arg in argv[1:]:
    if arg.startswith('-'):
        options.append(arg[1:])
    else:
        if arg[-1]=='/':
            arg = arg[:-1]
        modules.append(arg)
if not modules:
    modules.append('common')

allsw = bool('all' in options)

for module in modules:
    setattr(__builtin__, 'TTZ_Compile_Switch_'+module, True)
    setattr(__builtin__, 'TTZ_Compile_All_Switch_'+module, allsw)
    importlib.import_module(module)
