#!/usr/bin/env python

from imp import load_source
from os.path import exists
from sys import argv

import common

if len(argv)<2 or not exists(argv[1]):
    raise RuntimeError('Need to specify config file!')
config = load_source('myconfig', argv[1])
for __, proc in config.__dict__.iteritems():
    if isinstance(proc, common.Process):
        break
else:
    raise RuntimeError('Need to specify Process object in config file!')
name, mode, sample = None, None, None
part, firstevent, lastevent = None, None, None
if len(argv)>=3:
    name = argv[2]
if len(argv)>=4:
    mode = int(argv[3])
if len(argv)>=5:
    sample = int(argv[4])
if len(argv)>=6:
    part = int(argv[5])
if len(argv)>=7:
    firstevent = int(argv[6])
if len(argv)>=8:
    lastevent = int(argv[7])
proc.run(
    name=name, mode=mode, sample=sample, part=part,
    boundaries=(firstevent, lastevent)
)
